config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'sessions#new'

  resources :scraps, only: [:index]
  
end

app/models/user.rb
class User < ActiveRecord::Base

    before_save	{self.email	= email.downcase}

    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
    validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  
end

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController

    layout 'admin'

    def index
        images = 0
        css = 0
        css_inside = 0
        @scraps = []

        if params[:web_url]
            page = HTTParty.get(params[:web_url])
            parse_page = Nokogiri::HTML(page)

            hash = { 
                images: parse_page.search('img').count, 
                css: parse_page.search('style').count,
                css_inside: parse_page.css('body', 'style').count
            }

            @scraps.push(hash)
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to scraps_url
        else
            flash.now[:danger] = 'Email o contraseña invalido'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
        session[:user_name] = user.name
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def logged_in_user
      unless logged_in?
         flash[:danger] = "Please log in."
         redirect_to root_url
      end
   end

    def log_out
        reset_session
        @current_user = nil
    end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Position test</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.css"></script>
    <%= csrf_meta_tags %>

</head>

<body>

    <div id="wrapper">

        <nav class="navbar-default navbar-static-side" role="navigation">

            <div class="sidebar-collapse">

                <ul class="nav" id="side-menu">

                    <li class="nav-header">
                    
                        <div class="dropdown profile-element text-center">

                            <h2 style="margin-top: 0px; color: #ffffff; font-weight: 300; text-shadow: 1px 1px 1px #000000">POSITION TEST</h2>

                            <br>
                            <br>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-b-xs"><strong class="font-bold shadow"><%= session[:user_name] %></strong></span>
                                    <span class="text-xs block shadow">
                                        Administrador 
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element" style="color: #ffffff; font-weight: 300; text-shadow: 1px 1px 1px #000000">
                            
                        </div>
                    </li>

                    <li class="<%= 'active' if params[:controller] == 'scraps' %>">
                        <a href="<%= url_for(action: 'index', controller: '/scraps') %>">
                            <i class='fa fa-search shadow'></i>
                            <span class='nav-label shadow'>Nueva busqueda</span>
                        </a>
                    </li>

                </ul>

            </div>

        </nav>

        <div id="page-wrapper" class="white-bg">

            <div class="row border-bottom">
                <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm welcome-message">Bienvenido <%= session[:user_name] %>.</span>
                        </li>
                        <li>
                            <%=	link_to	'<i class="fa fa-sign-out"></i> Logout'.html_safe, logout_path, method: :delete %>
                        </li>
                    </ul
                </nav>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="wrapper wrapper-content">
                        <div class="row">
                            <div class="col-lg-12">
                                <%= yield %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer">
                <div class="pull-right">
                    Position test
                </div>
                <div>
                    Manuel Michelangelli &copy; 2017
                </div>
            </div>

        </div>

    </div>

    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Position test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scraps/index.html.erb
<div class="ibox float-e-margins">

    <div class="ibox-title">

        <h5>Busqueda</h5>

    </div>

   <div class="ibox-content">

       <div class="row">

           <div class="col-md-4">

               <%= form_tag(scraps_path, :method => "get", id: "search-form") do %>
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= label_tag :web_url, 'URL', :class => "text-primary" %>
                            <%= text_field_tag :web_url, params[:web_url], class: "form-control input-sm", required: true %>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <button id="search-btn" class="btn btn-primary btn-block">Verificar</button>
                        </div>
                    </div>
               <% end %>

           </div>

           <br>

           <div class="col-md-8">
                <div class="table-responsive">

                    <% if @scraps.count > 0 %>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Imagenes</th>
                                    <th>CSS</th>
                                    <th>CSS en html</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @scraps.each do |scrap| %>
                                    <tr>
                                        <td><%= scrap[:images] %></td>
                                        <td><%= scrap[:css] %></td>
                                        <td><%= scrap[:css_inside] %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    <% end %>

                </div>
           </div>
       
       </div>

    
   </div>

</div>